name: MC-Plugin
version: '${project.version}'
main: me.qiuchen.mcplugin.Main
api-version: '1.20'
website: https://github.com/xXQiuChenXx/MC-Plugin
softdepend: [PlaceholderAPI]
commands:
  mcp:
    description: Say Hi to Minecraft Dev
    usage: /<command> [good/reload]
    permission: mc.use
    permission-message: "You don't have permission to use this command."
  database:
    description: Test database query
    usage: /<command>
    permission: mc.use
    permission-message: "You don't have permission to use this command."
  fly:
    description: Fly Like a bird
    usage: /<command>
    permission: mcp.fly
    permission-message: "You don't have permission to use this command."

permissions:
  mcp.use:
    description: "Allows you to use the MC Plugin"
    default: op
  mcp.fly:
    description: "Allows you to use the MC Plugin"
    default: op
  mcp.fly.other:
    description: "Allows you to use the MC Plugin"
    default: op
  mcp.reload:
    description: "Allows you to reload the plugin"
    default: op